CREATE DATABASE [ApressFinancial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ApressFinancial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.DEV1\MSSQL\DATA\ApressFinancial.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ApressFinancial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.DEV1\MSSQL\DATA\ApressFinancial_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ApressFinancial] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [ApressFinancial] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ApressFinancial] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ApressFinancial] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ApressFinancial] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ApressFinancial] SET ARITHABORT OFF 
GO
ALTER DATABASE [ApressFinancial] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ApressFinancial] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ApressFinancial] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [ApressFinancial] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ApressFinancial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ApressFinancial] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ApressFinancial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ApressFinancial] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ApressFinancial] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ApressFinancial] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ApressFinancial] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ApressFinancial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ApressFinancial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ApressFinancial] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ApressFinancial] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ApressFinancial] SET  READ_WRITE 
GO
ALTER DATABASE [ApressFinancial] SET RECOVERY FULL 
GO
ALTER DATABASE [ApressFinancial] SET  MULTI_USER 
GO
ALTER DATABASE [ApressFinancial] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ApressFinancial] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ApressFinancial] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ApressFinancial]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ApressFinancial] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
